CREATE USER 'spring'@'%' IDENTIFIED BY 'spring';

GRANT SELECT ON *.* TO 'spring'@'%';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `springlab`.* TO 'spring'@'%';

-- GRANT ALL PRIVILEGES ON springlab.* TO spring;